server:
  port: 80

spring:
  thymeleaf:
    cache: false
  datasource:
   driver-class-name: com.mysql.cj.jdbc.Driver
   url: jdbc:mysql://localhost:3306/signuphere?serverTimezone=GMT%2B8&characterEncoding=UTF-8
   username: root
   password: 123456
   max-idle: 10
   max-wait: 10000
   min-idle: 5
   initial-size: 5